# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Rich Fairhurst
tagline:             'I do stuff. I go places. I write really boring bios'
description:         'I do stuff. I go places. I write really boring bios'
url:                 http://www.richfairhurst.co.uk
baseurl:             ''

# About/contact
author:
  name:              Rich Fairhurst
  url:               https://twitter.com/richfairhurst
  email:             rich[at]richfairhurst.co.uk

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 2
paginate_path: "/blog/page:num"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
